name: Run Terminal Emulator

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-terminal:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install paramiko

    - name: Run terminal emulator
      run: python terminal_emulator.py